import { sb } from "./supabase.js";
import { $, toast, setTitle, escapeHtml, openModal } from "./ui.js";
import { renderTeacher } from "./teacher.js";
import { renderStudent } from "./student.js";
import { renderAdmin } from "./admin.js";
let profile=null, session=null, currentPage="dashboard";
async function loadProfile(){const {data:{user}}=await sb.auth.getUser();if(!user)return null;const {data,error}=await sb.from("profiles").select("*").eq("id",user.id).single();if(error)throw error;return data}
function nav(role){const items=role==="admin"?[['dashboard','⌂','Удирдлагын самбар'],['users','♙','Хэрэглэгчид'],['classes','▦','Ангиуд'],['reports','◒','Тайлан'],['notifications','◔','Мэдэгдэл']]:role==="teacher"?[['dashboard','⌂','Dashboard'],['courses','▦','Миний хичээлүүд'],['exams','✎','Шалгалт'],['results','◒','Дүнгийн журнал'],['notifications','◔','Мэдэгдэл']]:[['dashboard','⌂','Dashboard'],['courses','▦','Миний хичээлүүд'],['exams','✎','Шалгалтууд'],['results','◒','Миний дүн'],['leaderboard','♛','Leaderboard'],['notifications','◔','Мэдэгдэл']];
$("#nav").innerHTML=items.map(([id,icon,label])=>`<button class="nav-btn" data-page="${id}"><span>${icon}</span>${label}</button>`).join("");document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>route(b.dataset.page))}
async function showApp(){$("#auth-view").classList.add('hidden');$("#app-view").classList.remove('hidden');$("#user-mini").innerHTML=`<div class="user-avatar">${escapeHtml((profile.full_name||'U').slice(0,1).toUpperCase())}</div><div><b>${escapeHtml(profile.full_name)}</b><small>${escapeHtml(profile.email||'')} · ${escapeHtml(profile.role)}</small></div>`;$("#profile-btn").textContent=(profile.full_name||'U').slice(0,1).toUpperCase();nav(profile.role);route('dashboard')}
function showAuth(){$("#auth-view").classList.remove('hidden');$("#app-view").classList.add('hidden')}
async function route(page){currentPage=page;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$("#breadcrumb").textContent=`EDU+ / ${page}`;try{if(profile.role==='admin')await renderAdmin(page,profile);else if(profile.role==='teacher')await renderTeacher(page,profile);else await renderStudent(page,profile)}catch(e){console.error(e);toast(e.message||'Алдаа гарлаа')}}
$("#login-tab").onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$("#login-tab").classList.add('active');$("#login-form").classList.remove('hidden');$("#signup-form").classList.add('hidden')};
$("#signup-tab").onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$("#signup-tab").classList.add('active');$("#signup-form").classList.remove('hidden');$("#login-form").classList.add('hidden')};
$("#login-form").onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$("#login-email").value.trim(),password:$("#login-password").value});if(error)return toast(error.message);profile=await loadProfile();showApp()};
$("#signup-form").onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.auth.signUp({email:$("#signup-email").value.trim(),password:$("#signup-password").value,options:{data:{full_name:$("#signup-name").value.trim()}}});if(error)return toast(error.message);if(data.session){profile=await loadProfile();showApp()}else toast('Бүртгэл үүслээ. Имэйлээ шалгана уу.')};
$("#logout-btn").onclick=async()=>{await sb.auth.signOut();profile=null;session=null;showAuth()};$("#refresh-btn").onclick=()=>route(currentPage);$("#profile-btn").onclick=()=>openModal(`<h2>Миний профайл</h2><div class="profile-card"><div class="profile-big">${escapeHtml((profile.full_name||'U').slice(0,1).toUpperCase())}</div><h3>${escapeHtml(profile.full_name)}</h3><p class="muted">${escapeHtml(profile.email||'')}</p><span class="badge">${escapeHtml(profile.role)}</span></div>`);
sb.auth.onAuthStateChange(async(_event,s)=>{session=s;if(s&&!profile){try{profile=await loadProfile();await showApp()}catch(e){console.error(e)}}if(!s){profile=null;showAuth()}});
const {data:{session:s}}=await sb.auth.getSession();session=s;if(session){try{profile=await loadProfile();if(profile)showApp();else showAuth()}catch(e){console.error(e);showAuth()}}else showAuth();
